# ---------- DATASOURCE (MySQL) ----------
#spring.datasource.url=jdbc:mysql://localhost:3306/pca_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#spring.datasource.username=root
#spring.datasource.password=test
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP (connection pool) sensible defaults
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# ---------- JPA / HIBERNATE ----------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ---------- LOGGING ----------
# set root logger to INFO (everything above or equal to INFO)
# make our app package info
logging.level.com.pca=INFO
# Spring framework logs (you may lower to WARN in prod)
logging.level.org.springframework=INFO

# ---------- SERVER ----------
server.port=5000
server.address=0.0.0.0


# ---------- OTHER ----------
# Enable actuator endpoints in prod if needed (careful with security)
management.endpoints.web.exposure.include=health,info

# Internationalization / timezone behaviour (if needed)
spring.jackson.time-zone=UTC
